# Generated by Django 4.0.3 on 2022-04-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leave_leavetype_leave_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
    ]
