# Generated by Django 4.0.3 on 2022-04-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
