# Generated by Django 4.0.3 on 2022-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('Other', 'Others')], default='sick', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(help_text='Add additional information for leave', max_length=500, verbose_name='Reason for Leave'),
        ),
    ]
