# Generated by Django 4.0.3 on 2022-04-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp383', max_length=70),
        ),
    ]
