# Generated by Django 4.0.3 on 2022-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_department_created_date_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='history',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp125', max_length=70),
        ),
    ]
