# Generated by Django 4.0.3 on 2022-04-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accnum',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='First Bank Plc', max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp639', max_length=70),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('nepali', 'NEPALI'), ('hindi', 'HINDI')], default='english', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='00,000.00', max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.department'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
