# Generated by Django 4.0.3 on 2022-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_employee_joined_employee_password_employee_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp812', max_length=70),
        ),
    ]
