# Generated by Django 4.0.3 on 2022-04-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_profile_email_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
