# Generated by Django 4.0.3 on 2022-04-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0032_rename_firstname_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
