# Generated by Django 4.0.3 on 2022-04-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0040_department_user_alter_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
    ]
