# Generated by Django 4.0.3 on 2022-05-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0042_alter_attendance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
